### ISSUE TITLE
If you put a URL escaped in the config YAML, it gets unescaped when making request to the real server

### ISSUE THREAD

**Issue by quii** [quii/mockingjay-server#10]
/document/10.1007%2Fs00414-006-0114-x

/document/10.1007/s00414-006-0114-x

**Comment by quii** [comment]
Also true when using the fake server

````bash
Chriss-MacBook-Pro:mockingjay-server qui$ curl -v http://localhost:9090/document/10.1007%2Fs00414-006-0114-x
* Hostname was NOT found in DNS cache
*   Trying ::1...
* Connected to localhost (::1) port 9090 (#0)
> GET /document/10.1007%2Fs00414-006-0114-x HTTP/1.1
> User-Agent: curl/7.37.1
> Host: localhost:9090
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Date: Mon, 18 May 2015 12:11:44 GMT
< Content-Length: 526
< Content-Type: text/plain; charset=utf-8
< 
message: Endpoint not found
request:
  uri: /document/10.1007/s00414-006-0114-x
  method: GET
  headers:
    Accept: '*/*'
    User-Agent: curl/7.37.1
  body: ""
endpointsavailable:
- name: Some article on content api
  request:
    uri: /document/10.1007%2Fs00414-006-0114-x
    method: GET
    headers: {}
    body: ""
  response:
    code: 200
    body: <Publisher><meta:Info xmlns:meta="http://www.springer.com/app/meta"><meta:Date>2006-09-01</meta:Date></meta:Info></Publisher>
    headers:
      content-type: text/json
* Connection #0 to host localhost left intact
````

**Comment by quii** [comment]
Example yaml 

````
---
 - name: Some article on content api
   request:
     uri: /document/10.1007%2Fs00414-006-0114-x
     method: GET
   response:
     code: 200
     body: '<Publisher><meta:Info xmlns:meta="http://www.springer.com/app/meta"><meta:Date>2006-09-01</meta:Date></meta:Info></Publisher>'
     headers:
       content-type: text/json
````
