### ISSUE TITLE
Proposal: Allow returning simple code results 

### ISSUE THREAD

**Issue by aronchick** [quii/mockingjay-server#13]
I'd love to randomize the results - no different than allowing simple code execution. In this case, it might look like the following

```yaml
---
 - name: Test endpoint
   request:
     uri: /hello
     method: GET
   response:
     code: 200
     body: '{"message": "hello, world", "temperatureOutside": `fmt.Sprintf("%s", rand.Intn(100)))`}'
     headers:
       content-type: text/json
```

There is a much much much less ugly way to do it than the above, but you get the idea.
