### ISSUE TITLE
Be able to define different response body for different response code

### ISSUE THREAD

**Issue by jzk** [quii/mockingjay-server#26]
So when it's sending 400 response defined in the monkey-business.yaml instead of normal 200, it would be nice to have server return different response body

**Comment by quii** [comment]
Just to clarify:

So currently it can send a different body at random times and different status codes too

But you want it so you can define multiple "monkey business" to happen at the same time. So something like

````yaml
- body: "This is wrong :( "
  status: 400
  frequency: 0.5
````

Correct?

**Comment by jzk** [comment]
yea. when defining monkey business like this, I would want it can return different pre-defined body like this example.

**Comment by quii** [comment]
Seems like a good idea to me, will try and hack something out soon :)

**Comment by quii** [comment]
@jzk It seems by chance, this already works

`monkey.yaml`
````yaml
---
# Writes a different body 50% of the time
- body: "This is wrong :( "
  status: 400
  frequency: 0.5
````

`example.yaml`
````yaml
---
 - name: Test endpoint
   request:
     uri: /hello
     method: GET
   response:
     code: 200
     body: '{"message": "hello, world"}'
     headers:
       content-type: text/json
````
mockingjay-server -config=example.yaml -monkeyConfig=monkey.yaml

Could you give it a go and let me know if this is what you need?
