### ISSUE TITLE
When comparing request bodies (and probably response), if it is JSON it shouldn't be whitespace sensitive

### ISSUE THREAD

**Issue by quii** [quii/mockingjay-server#3]
```yaml
---
    - name: Valid login details
      request:
        uri: /user-token
        method: POST
        body: '{"email":"foo@bar.com","password":"xxx"}'
      response:
        code: 200
        body: '{"token": "1234abc"}'
````

Should be compatible with a request body that has spacing in it. Currently it isn't.
