### ISSUE TITLE
Regex/Glob matching for fake server

### ISSUE THREAD

**Issue by quii** [quii/mockingjay-server#31]
## Background

People in the past have asked for wildcards/regex/glob for matching request URLs when running a fake server. I have had to say no because it's difficult to then keep the CDC functionality working. 

e.g.

`uri: /foo/{id}` 

What "id" do I send to the real server in CDC mode? 

## Possible solution

Have a second, optional field in the request section which defines a regex of the URL. 
````yaml
---
 - name: Test endpoint
   request:
     uri: /hello/world
     regex: /hello/{A-Z} 
     method: GET
   response:
     code: 200
     body: '{"message": "hello, world"}'
     headers:
       content-type: text/json
````

Note: Glob might be friendlier, and could be an option. But for now will assume regex.

### On startup
- Make sure that the normal URI matches the regex. 
- This ensures that when you're running as a fake server with variable parameters that it is still close to what call the CDC will make. 
- That way you cant run in to a scenario where all your tests are hitting a "variable" URL that doesn't actually exist. 

### In fake mode
When a request arrives, obey the usual matching orders but if the URI doesnt match the "concrete" one, then see if it matches the regex. Need to make sure exact URLs are checked first. 
````yaml
---
 - name: Test endpoint2
   request:
     uri: /hello/world
     regex: /hello/{A-Z} 
     method: GET
   response:
     code: 200
     body: '{"message": "hello, world"}'
     headers:
       content-type: text/json

 - name: Test endpoint
   request:
     uri: /hello/chris
     method: GET
   response:
     code: 200
     body: '{"message": "hello, chris"}'
     headers:
       content-type: text/json
````

In this scenario if you send `/hello/chris` it should be the second one that "wins", not the first one by virtue of the regex

### CDC mode
No changes

Credit to @chandley and @thecodeite
