### ISSUE TITLE
Headers check is too strict

### ISSUE THREAD

**Issue by quii** [quii/mockingjay-server#42]
Given 

````yaml
---
---
 - name: Issue 42 is where extraneous headers sent will trigger a 404. It should ignore unknown headers
   request:
     uri: /test
     method: POST
     headers:
      content-type: application/json
   response:
     code: 200
````

If a request is sent with *other* headers, such as `Content-Length` it is seen as not matching. 

This is because mockingjay/request.go hopes that the two header arrays match (deepEqual). https://github.com/quii/mockingjay-server/blob/master/mockingjay/request.go#L95

Instead it should see if the incoming requests just contains all the ones we expect, ignoring others.

Automated tests are in server_test.go . The test for this should probably go in request_test.go
