### ISSUE TITLE
Sending form data doesn't seem to work well

### ISSUE THREAD

**Issue by quii** [quii/mockingjay-server#46]
````yaml
---
 - name: Response from Mailgun receiving message on Activism
   cdcdisabled: false
   request:
     uri: /v3/aslive.activistmonitor.com/messages
     method: POST
     body: 'from=info%40sandbox47ad8d7815c24338afa44c16a9492f36.mailgun.org&to=test.notifications%40mergermarket.com&subject=send%20a%20message&text=this%20is%20a%20message&html=foo&v%3Aenv=local&v%3AmatchId=cj&v%3Aapplication=notifications'
   response:
     code: 200
````

This doesn't seem to send the data correctly to mailgun as we get a 400. The interface here for users sucks too, perhaps adding a formdata field for the YAML will improve things
