### ISSUE TITLE
There were duplicated requests found ...

### ISSUE THREAD

**Issue by tochka** [quii/mockingjay-server#52]
There were duplicated requests found because request body limited 50 bytes
https://github.com/quii/mockingjay-server/blob/4a9da103e0c6997bdc069e3cdce5dc09faafcf92/mockingjay/request.go#L154

**Comment by quii** [comment]
Hey

Thanks for opening this. Could you perhaps link to your configuration that is causing the error too? Looking at the code i cant believe this hasn't come up before!

But this looks like a good catch, will check it out properly later today.

**Comment by tochka** [comment]
It's my config file there are 2 endpoints with different body request
```yaml
 - name: Get app info
   request:
     uri: /info
     method: POST
     body: '{"ids":["f33db9b75f3fda65449982df3580a9caf5914aa174d5833b40cf5893b9674780"]}' # * matches any body
   response:
     code: 200
     body: '[{"id":"f33db9b75f3fda65449982df3580a9caf5914aa174d5833b40cf5893b9674780","meta":{"created_at":"today","signs":{"f33db9b75f3fda65449982df3580a9caf5914aa174d5833b40cf5893b9674780":"MFEwDQYJYIZIAWUDBAICBQAEQIuxm8ZWiD+xMzb9OwVo2Qv3LLj49nM5/6BJGxs858n8sRrP+xFZu1ZGiGlLMiRPgoGZiFMGpxnk47Zw/+YMUww=","17ea725ea3a0892522c04761cef46861778d3ebb23524356bbef9415fda011c7":"MFEwDQYJYIZIAWUDBAICBQAEQJcQEn1WdmeA3Ya2AMfDFq83sT5CLLjlrM7nAKwyIqhIHIlPyuI8cYjeURlC6FWAzqxHYKrmv4+KGUy+cSXJHwo="}}}]'
     headers:
       content-type: application/json
 - name: Get app and master info
   request:
     uri: /info
     method: POST
     body: '{"ids":["f33db9b75f3fda65449982df3580a9caf5914aa174d5833b40cf5893b9674780","c11c1bceec06828adbc142b84a684874bf3922c93c5cddedc7a8a8ce2ca0f123"]}' # * matches any body
   response:
     code: 200
     body: '[{"id":"c11c1bceec06828adbc142b84a684874bf3922c93c5cddedc7a8a8ce2ca0f123","meta":{"created_at":"today","signs":{"c11c1bceec06828adbc142b84a684874bf3922c93c5cddedc7a8a8ce2ca0f123":"MFEwDQYJYIZIAWUDBAICBQAEQJKXM/7rWu5PMbZGq1Ath2+0vO3OCpe1Led/BoMg1/mxdFaP4Cp9cLkZ30IUWnma5iuo2IHCxLRShc43wEYjswQ=","17ea725ea3a0892522c04761cef46861778d3ebb23524356bbef9415fda011c7":"MFEwDQYJYIZIAWUDBAICBQAEQClJoBsrX+X/8rJszIqoubdrPNCh95eLCJ7qdt3DBUZqaFOIG7YE7IVbYw89qBM2+hKYLg2C1LOAeVDPvT3PRQ0=","f33db9b75f3fda65449982df3580a9caf5914aa174d5833b40cf5893b9674780":"MFEwDQYJYIZIAWUDBAICBQAEQFVOx2FLWDH+KkBiqYtLTQyIuTPcl2liX9UAzi/Nd1PcaAo36adMxPpGut+JyzkdJ0vhxcWqvzsXMvDm+Gs2CQU="}}},{"id":"f33db9b75f3fda65449982df3580a9caf5914aa174d5833b40cf5893b9674780","meta":{"created_at":"today","signs":{"f33db9b75f3fda65449982df3580a9caf5914aa174d5833b40cf5893b9674780":"MFEwDQYJYIZIAWUDBAICBQAEQIuxm8ZWiD+xMzb9OwVo2Qv3LLj49nM5/6BJGxs858n8sRrP+xFZu1ZGiGlLMiRPgoGZiFMGpxnk47Zw/+YMUww=","17ea725ea3a0892522c04761cef46861778d3ebb23524356bbef9415fda011c7":"MFEwDQYJYIZIAWUDBAICBQAEQJcQEn1WdmeA3Ya2AMfDFq83sT5CLLjlrM7nAKwyIqhIHIlPyuI8cYjeURlC6FWAzqxHYKrmv4+KGUy+cSXJHwo="}}}]'
     headers:
       content-type: application/json
 ```
Full error log:
```
 2017/08/24 07:12:23 There were duplicated requests found [POST /info Body: [{"ids":["f33db9b75f3fda65449982df3580a9caf5914aa17...]]
```
Short answer:
You check all incoming fake request on [duplicate](https://github.com/quii/mockingjay-server/blob/a96bdcd7d095cc60f3290887c8a2f9b88074fbf9/mockingjay/fakeendpoint.go#L87)
And Request.String() return all information in string representation for more human readable so [request body is limited by 50 bytes](https://github.com/quii/mockingjay-server/blob/a96bdcd7d095cc60f3290887c8a2f9b88074fbf9/mockingjay/request.go#L155)
